---
- name: Workstation setup (distribution independent)
  hosts: all
  vars_files:
    - vars/default.yml
  tasks:
    - name: "adding existing user '{{ username }}' to group docker"
      become: yes
      user:
        name: "{{ username }}"
        groups: docker
        shell: /usr/bin/fish
        append: yes
    - name: Clone fish config repository
      git:
        repo: https://github.com/BlacCello/fish.git
        dest: "{{ playbook_dir }}/tmp/git/fish"
        clone: yes
        update: yes
    - name: Call setup script for fish
      ansible.builtin.shell: |
        "/home/{{ username }}/git/fish/create-symlinks.sh" >> "{{ playbook_dir }}/tmp/fish.log"
  roles:
    - binenv
    - fish
    - fonts
    - gnome
