---
roles:
  - name: andrewrothstein.k3d
  - name: andrewrothstein.kind
  - name: andrewrothstein.kubectl
  - name: gantsign.visual-studio-code
  - name: geerlingguy.docker
  - name: geerlingguy.helm
  - name: petermosmans.customize-gnome
  - name: samdoran.fish
