---
- name: Ubuntu 22.04 setup
  hosts: all
  vars_files:
    - vars/default.yml
    - vars/ubuntu.yml
  tasks:
    - name: Install apt packages
      become: yes
      apt:
        name: "{{ generic_packages }} + {{ distribution_packages }}"
        state: present
    - name: Create symbolic link for bat
      become: yes
      file:
        src: "/usr/bin/batcat"
        dest: "/usr/local/bin/bat"
        state: link
    - name: Create symbolic link for fd
      become: yes
      file:
        src: "/usr/bin/fdfind"
        dest: "/usr/local/bin/fd"
        state: link
- name: Ubuntu 22.04 setup
  hosts: all
  become: yes
  roles:
    - andrewrothstein.k3d
    - andrewrothstein.kind
    - andrewrothstein.kubectl
    - gantsign.visual-studio-code
    - geerlingguy.docker
    - role: geerlingguy.helm
      vars:
        helm_version: "v3.13.0"
    - samdoran.fish
- ansible.builtin.import_playbook: generic.yml
