---
- name: Install apt packages
  become: yes
  apt:
    name:
      - gir1.2-gda-5.0
      - gir1.2-gsound-1.0
      - gnome-shell-extension-manager
    state: present
  when: ansible_pkg_mgr == "apt"
- name: Install pacman packages
  become: yes
  community.general.pacman:
    name:
      - libgda6
      - gnome-shell-extension-manager
    state: present
  when: ansible_pkg_mgr == "pacman"
- ansible.builtin.include_role:
    name: petermosmans.customize-gnome
