---
- name: Install pip requirements
  ansible.builtin.pip:
    name:
      - github3.py

- name: Check if binenv is installed
  command: which binenv
  register: binenv_installed
  changed_when: false
  failed_when: false

- debug:
    msg: Return code of 'which binenv' is {{ binenv_installed.rc }}

- name: "Get Latest Release from Github"
  community.general.github_release:
    user: devops-works
    repo: binenv
    action: latest_release
    # token: "{{ github_token }}"
  register: release
  when: binenv_installed.rc != 0

- name: Print Latest release
  ansible.builtin.debug:
    var: release
  when: binenv_installed.rc != 0

- name: Download
  ansible.builtin.get_url:
    url: https://github.com/devops-works/binenv/releases/download/{{release.tag}}/binenv_linux_amd64
    dest: /tmp/binenv
    mode: a+x
  when: binenv_installed.rc != 0

- name: Install binenv with binenv
  ansible.builtin.shell: "/tmp/binenv update && /tmp/binenv install binenv"
  when: binenv_installed.rc != 0

- name: Delete downloaded binenv
  ansible.builtin.file:
    path: /tmp/binenv
    state: absent
  when: binenv_installed.rc != 0

- name: Install binaries
  loop: "{{binenv_install}}"
  include_tasks: binary.yml
  loop_control:
    loop_var: binary
